[project]
name = "opsbox-aws-iam-mfa-enabled"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = "==3.11.*"
dependencies = [
    "loguru>=0.7.2",
    "pluggy>=1.5.0",
]

[project.entry-points.'opsbox.plugins']
opsbox_aws_iam_mfa_enabled = "mfa_enabled.mfa_enabled:IAMMFADisabled"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"mfa_enabled" = ["*.rego", "manifest.toml"]